### PR TITLE
Fix return type of MODEL::calcprobin()

### PR DESCRIPTION
**Pull request by rwj11**
Fix for crash

### CODE REVIEW

**Comment by ianhinder** [comment]
I think Chris was also fixing this - should we wait for his own fix?

**Comment by rwj11** [comment]
dev being broken this badly is a blocker on anything else.

**Comment by ianhinder** [comment]
I don't understand this; why would changing the return type of MODEL::calcprobin from double to void avoid a double free?  Calls to this function don't seem to look at the return value anyway. I think I must be missing something!

**Comment by rwj11** [comment]
Try this

    #include <stdio.h>
    double foo() { printf("In the foo\n"); }
    void bar() { printf("In the bar!\n"); }
    int main() { foo(); }

See under [NasalDemons](http://www.catb.org/jargon/html/N/nasal-demons.html) in C++ lore.  `main` is a special case in C++ https://en.cppreference.com/w/cpp/language/return

**Comment by ianhinder** [comment]
Ah I think I see now.  It wasn't obvious from the diff shown in the PR, but the other important ingredient to understand this is that there is no value returned from the function.  So the function should have been returning double, it wasn't, and the compiler thought it was OK to leave it as a warning and corrupt memory?  I'd love to see why anyone thought that was a good call!  Merging.

**Comment by rwj11** [comment]
> I'd love to see why anyone thought that was a good call!

"Phone a friend" came up with this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43943

**Pull request merged**
